''' Project Euler Problem 2: 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''
import array
myList=[1,1]
#def createFibonacciSeries():
#for i in range(1,10):
j=0
sum=0
while(myList[j+1]):
	myList.append(0)
	myList[j+2]=myList[j+1]+myList[j]
	if myList[j+2] > 4000000:
		myList[j+2]=0
	if myList[j+2]%2==0:
		sum=sum+myList[j+2]
		#print(myList[j+2])
	j=j+1
print(sum)	
		
	